- name: Find ssh host keys to remove
  ansible.builtin.find:
    paths: /etc/ssh/
    patterns: "ssh_host_*"
    use_regex: true
  register: ssh_host_keys_to_delete

- name: Remove ssh host keys
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ ssh_host_keys_to_delete.files }}"
