all:
  hosts:
    node1:
      ansible_host: node1.vault.tld
    node2:
      ansible_host: node2.vault.tld
    node3:
      ansible_host: node3.vault.tld

  children:
    vault:
      hosts:
        node1:
          raft_node_id: node1
        node2:
          raft_node_id: node2
        node3:
          raft_node_id: node3
    proxy:
      hosts:
        node1:
        node2:
        node3:
