[tool.poetry]
name = "homelab"
version = "0.1.0"
description = ""
authors = ["Kirill Aleksandrov <kirill.aleks.swe@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.13"
ansible = "12.0.0"

[tool.poetry.group.dev.dependencies]
ansible-lint = "25.9.1"
