- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: true
    purge: true

- name: Clean apt cache
  ansible.builtin.apt:
    clean: true
