- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    update_cache: true

- name: Render HAProxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '644'

- name: Start and enable HAProxy service
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true
