- name: Truncate machine-id
  community.general.filesize:
    path: /etc/machine-id
    size: 0

- name: Remove logs and artifacts so cloud-init can re-run
  ansible.builtin.command: cloud-init clean
  tags:
    - skip_ansible_lint

- name: Configure data sources
  ansible.builtin.copy:
    src: 99_pve.cfg
    dest: /etc/cloud/cloud.cfg.d/99_pve.cfg
    mode: '0644'
