repositories:
  # - name: hashicorp
  #   url: https://helm.releases.hashicorp.com
  - name: nginx-ingress
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  # - name: external-dns
  #   url: https://kubernetes-sigs.github.io/external-dns/
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/

releases:
  # - name: vault-secrets-operator
  #   namespace: vault-secrets-operator
  #   chart: hashicorp/vault-secrets-operator
  #   version: 0.7.1
  - name: nginx-ingress
    namespace: nginx-ingress
    chart: nginx-ingress/ingress-nginx
    version: 4.11.3
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.16.1
    set:
      - name: crds.enabled
        value: true
  # - name: external-dns
  #   namespace: external-dns
  #   chart: external-dns/external-dns
  #   version: 1.14.5
  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: 7.10.0
    values:
      - app:
          ingress:
            enabled: true
            hosts:
              - dashboard.kubernetes.homelab
            ingressClassName: nginx
            issuer:
              name: vault-issuer
            annotations:
              cert-manager.io/private-key-algorithm: ECDSA
      - ./kubernetes-dashboard/extras_manifests.yaml.gotmpl
